project01/carts/urls.py
from django.conf.urls import url


from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view,
     )

urlpatterns = [
    url(r'^$' , cart_home, name="home"),
    url(r'^update/$' , cart_update, name="update"),
    url(r'^checkout/$' , checkout_home, name="checkout"),
   	url(r'^checkout/success/$' , checkout_done_view, name="success"),

]

project01/products/urls.py
from django.conf.urls import url


from .views import (
    ProductListView,
    ProductDetailSlugView
     )

urlpatterns = [
    url(r'^$' , ProductListView.as_view(), name="list"),
    url(r'^(?P<slug>[\w-]+)/$' , ProductDetailSlugView.as_view(), name="detail")
]

project01/project01/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView


from carts.views import cart_detail_api_view
from addresses.views import checkout_address_create_view,checkout_address_reuse_view
from accounts.views import LoginView, RegisterView, guest_register_view
from billing.views import payment_method_view, payment_method_createview
from .views import home_page, about_page, contact_page
from marketing.views import MarketingPreferenceUpdateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$' ,home_page, name='home'),
    url(r'^about/$' ,about_page, name='about'),
    url(r'^contact/$' ,contact_page, name="contact"),
    url(r'^login/$' ,LoginView.as_view(), name='login'),
    url(r'^checkout/address/create/$',checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$',checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^register/guest$' ,guest_register_view, name='guest_register'),
    url(r'^logout/$' ,LogoutView.as_view(), name='logout'),
    url(r'^api/cart/$' ,cart_detail_api_view, name='api-cart'),
    url(r'^cart/' , include("carts.urls", namespace="cart")),
    url(r'^billing/payment-method/$' ,payment_method_view, name="billing-payment-method"),
    url(r'^billing/payment-method/create/$' ,payment_method_createview, name="billing-payment-method-endpoint"),
    url(r'^register/$' ,RegisterView.as_view(), name="register"),
    url(r'^bootstrap/$' ,TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^products/' , include("products.urls", namespace="products")),
    url(r'^edukacija/' , include("edukacija.urls", namespace="edukacija")),
    url(r'^settings/email/$',MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^search/' , include("search.urls", namespace="search")),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
        urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project01/templates/base/css.html
{% load static %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!-- jquery-confirm CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">

<!-- custom stripe styling -->

<link rel="stylesheet" type="text/css" href="{% static 'css/stripe-custom-style.css' %}">

<!-- font awsome -->
<link rel="stylesheet" href="font-awesome-4.7.0\css\font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">

project01/templates/base/forms.html
{% extends "base.html" %}

{% block content %}
<div class="col-12 col-md-6 mx-auto">
{% if title %}<h1 class="my-3">{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <button type='submit' class='btn btn-default'>Save</button>
</form>
</div>
{% endblock %}

project01/templates/base/js.html
{% load static %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>



<!-- <script src="{% static 'js/slideshow.js' %}" ></script> -->
<script src="{% static 'js/csrf_ajax.js' %}" ></script>
<!-- ecommerce custom js -->
<script src="{% static 'js/ecommerce.js' %}" ></script>
<!-- ecommerce main js -->
<script src="{% static 'js/ecommerce.main.js' %}" ></script>

<!-- jquery-confirm JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>
<!-- stiripe.js -->
<script src="https://js.stripe.com/v3/"></script>
<!-- js render -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.90/jsrender.min.js"></script>
{% include 'base/js_templates.html' %}

<!--<script src="{% static 'js/slideshow.js' %}" ></script>-->

project01/templates/base/js_templates.html
{% verbatim %}
<!-- stripe template form -->
<script id="stripeTemplate" type="text/x-jsrender">
    <form class='payment-form' action="" method="post" id="payment-form" data-token='{{:publishKey}}' data-next-url='{{:nextUrl}}'>
  <div class="form-row">
    <!-- <label for="card-element">
      Credit or debit card
    </label> -->
    <div id="card-element" class='form-control'>
      <!-- a Stripe Element will be inserted here. -->
    </div>
    <!-- Used to display form errors -->
    <div id="card-errors" role="alert"></div>
  </div>
  <button class='btn btn-primary my-3 btn-load'>{{:btnTitle }}</button>
    </form>
</script>
{% endverbatim %}

project01/templates/base/navbar.html
{% load static %}

{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}
{% url 'edukacija:list' as edukacija_list_url %}



<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
   <div class='container'>
  <a class="navbar-brand" href="{{ home_url }}">
    <img src="https://logopond.com/logos/449ad200552bfe13060fd7919cd6f362.png" width="30" height="30" class="d-inline-block align-top" alt="">
    PcelarRS
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Početna<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Kontakt</a>
      </li>
      <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
        <a class="nav-link" href="{{ product_list_url }}">Proizvodi</a>
      </li>
      <li class="nav-item {% if request.path == edukacija_list_url %}active{% endif %}">
        <a class="nav-link" href="{{ edukacija_list_url }}">Edukacija</a>
      </li>
      {% if request.user.is_authenticated %}
       <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
        <a class="nav-link" href="{{ logout_url }}">Logout</a>
      </li>
      {% else %}
       <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Registracija</a>
      </li>
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>
      {% endif %}
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ cart_url }}"><span class="navbar-cart-count">{{ request.session.cart_items }} </span> <i class="fa fa-shopping-cart" aria-hidden="true"></i></i></a>
      </li>

    </ul>
    {% include 'search/snippets/search-form.html' %}
  </div>
</div>
</nav>